DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "oauth_providers" CASCADE;
DROP TABLE IF EXISTS "user_oauth" CASCADE;
DROP TABLE IF EXISTS "oauth_registration" CASCADE;
DROP TABLE IF EXISTS "mfa_totp" CASCADE;