// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: oauth.proto

package pb

import (
	common "fbt/backend/internal/domain/auth/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{0}
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []string               `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *StatusReply) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type LoginReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RegistrationNeeded bool                   `protobuf:"varint,1,opt,name=registrationNeeded,proto3" json:"registrationNeeded,omitempty"`
	RegistrationID     string                 `protobuf:"bytes,2,opt,name=registrationID,proto3" json:"registrationID,omitempty"`
	Session            *common.Session        `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetRegistrationNeeded() bool {
	if x != nil {
		return x.RegistrationNeeded
	}
	return false
}

func (x *LoginReply) GetRegistrationID() string {
	if x != nil {
		return x.RegistrationID
	}
	return ""
}

func (x *LoginReply) GetSession() *common.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RegistrationID  string                 `protobuf:"bytes,1,opt,name=registrationID,proto3" json:"registrationID,omitempty"`
	Provider        string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	TokenID         string                 `protobuf:"bytes,3,opt,name=TokenID,proto3" json:"TokenID,omitempty"`
	Username        string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Email           string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	PasswordEnabled bool                   `protobuf:"varint,7,opt,name=passwordEnabled,proto3" json:"passwordEnabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_oauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetRegistrationID() string {
	if x != nil {
		return x.RegistrationID
	}
	return ""
}

func (x *RegisterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RegisterRequest) GetTokenID() string {
	if x != nil {
		return x.TokenID
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetPasswordEnabled() bool {
	if x != nil {
		return x.PasswordEnabled
	}
	return false
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *common.Session        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_oauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterReply) GetSession() *common.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_oauth_proto protoreflect.FileDescriptor

const file_oauth_proto_rawDesc = "" +
	"\n" +
	"\voauth.proto\x12\x05oauth\x1a\x13common/common.proto\"\x0f\n" +
	"\rStatusRequest\"+\n" +
	"\vStatusReply\x12\x1c\n" +
	"\tproviders\x18\x01 \x03(\tR\tproviders\"V\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\"\x8f\x01\n" +
	"\n" +
	"LoginReply\x12.\n" +
	"\x12registrationNeeded\x18\x01 \x01(\bR\x12registrationNeeded\x12&\n" +
	"\x0eregistrationID\x18\x02 \x01(\tR\x0eregistrationID\x12)\n" +
	"\asession\x18\x03 \x01(\v2\x0f.common.SessionR\asession\"\xe7\x01\n" +
	"\x0fRegisterRequest\x12&\n" +
	"\x0eregistrationID\x18\x01 \x01(\tR\x0eregistrationID\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x18\n" +
	"\aTokenID\x18\x03 \x01(\tR\aTokenID\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12(\n" +
	"\x0fpasswordEnabled\x18\a \x01(\bR\x0fpasswordEnabled\":\n" +
	"\rRegisterReply\x12)\n" +
	"\asession\x18\x01 \x01(\v2\x0f.common.SessionR\asession2\xac\x01\n" +
	"\x05OAuth\x124\n" +
	"\x06Status\x12\x14.oauth.StatusRequest\x1a\x12.oauth.StatusReply\"\x00\x12:\n" +
	"\bRegister\x12\x16.oauth.RegisterRequest\x1a\x14.oauth.RegisterReply\"\x00\x121\n" +
	"\x05Login\x12\x13.oauth.LoginRequest\x1a\x11.oauth.LoginReply\"\x00B(Z&internal/domain/auth/features/oauth/pbb\x06proto3"

var (
	file_oauth_proto_rawDescOnce sync.Once
	file_oauth_proto_rawDescData []byte
)

func file_oauth_proto_rawDescGZIP() []byte {
	file_oauth_proto_rawDescOnce.Do(func() {
		file_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oauth_proto_rawDesc), len(file_oauth_proto_rawDesc)))
	})
	return file_oauth_proto_rawDescData
}

var file_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_oauth_proto_goTypes = []any{
	(*StatusRequest)(nil),   // 0: oauth.StatusRequest
	(*StatusReply)(nil),     // 1: oauth.StatusReply
	(*LoginRequest)(nil),    // 2: oauth.LoginRequest
	(*LoginReply)(nil),      // 3: oauth.LoginReply
	(*RegisterRequest)(nil), // 4: oauth.RegisterRequest
	(*RegisterReply)(nil),   // 5: oauth.RegisterReply
	(*common.Session)(nil),  // 6: common.Session
}
var file_oauth_proto_depIdxs = []int32{
	6, // 0: oauth.LoginReply.session:type_name -> common.Session
	6, // 1: oauth.RegisterReply.session:type_name -> common.Session
	0, // 2: oauth.OAuth.Status:input_type -> oauth.StatusRequest
	4, // 3: oauth.OAuth.Register:input_type -> oauth.RegisterRequest
	2, // 4: oauth.OAuth.Login:input_type -> oauth.LoginRequest
	1, // 5: oauth.OAuth.Status:output_type -> oauth.StatusReply
	5, // 6: oauth.OAuth.Register:output_type -> oauth.RegisterReply
	3, // 7: oauth.OAuth.Login:output_type -> oauth.LoginReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_oauth_proto_init() }
func file_oauth_proto_init() {
	if File_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauth_proto_rawDesc), len(file_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oauth_proto_goTypes,
		DependencyIndexes: file_oauth_proto_depIdxs,
		MessageInfos:      file_oauth_proto_msgTypes,
	}.Build()
	File_oauth_proto = out.File
	file_oauth_proto_goTypes = nil
	file_oauth_proto_depIdxs = nil
}
