version: "2"
linters:
  default: standard
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - dupword
    - embeddedstructfieldcheck
    - gochecknoinits
    - gosec
    - mnd
    - modernize
    - tagalign
    - usestdlibvars
    # - varnamelen
    - wastedassign
    - wsl_v5
