// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/bookkeeping/transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEntry) Reset() {
	*x = TransactionEntry{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEntry) ProtoMessage() {}

func (x *TransactionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEntry.ProtoReflect.Descriptor instead.
func (*TransactionEntry) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionEntry) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *TransactionEntry) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     int32                  `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetAccountID() int32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *Entry) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{2}
}

type GetAllReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionEntry []*TransactionEntry    `protobuf:"bytes,1,rep,name=transactionEntry,proto3" json:"transactionEntry,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllReply) Reset() {
	*x = GetAllReply{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReply) ProtoMessage() {}

func (x *GetAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReply.ProtoReflect.Descriptor instead.
func (*GetAllReply) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllReply) GetTransactionEntry() []*TransactionEntry {
	if x != nil {
		return x.TransactionEntry
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CreateRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CreateReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionEntry *TransactionEntry      `protobuf:"bytes,1,opt,name=transactionEntry,proto3" json:"transactionEntry,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateReply) Reset() {
	*x = CreateReply{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReply) ProtoMessage() {}

func (x *CreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReply.ProtoReflect.Descriptor instead.
func (*CreateReply) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReply) GetTransactionEntry() *TransactionEntry {
	if x != nil {
		return x.TransactionEntry
	}
	return nil
}

type UpdateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionEntry *TransactionEntry      `protobuf:"bytes,1,opt,name=transactionEntry,proto3" json:"transactionEntry,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetTransactionEntry() *TransactionEntry {
	if x != nil {
		return x.TransactionEntry
	}
	return nil
}

type UpdateReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionEntry *TransactionEntry      `protobuf:"bytes,1,opt,name=transactionEntry,proto3" json:"transactionEntry,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateReply) Reset() {
	*x = UpdateReply{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReply) ProtoMessage() {}

func (x *UpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReply.ProtoReflect.Descriptor instead.
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateReply) GetTransactionEntry() *TransactionEntry {
	if x != nil {
		return x.TransactionEntry
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_transaction_proto_rawDescGZIP(), []int{9}
}

var File_proto_bookkeeping_transaction_proto protoreflect.FileDescriptor

const file_proto_bookkeeping_transaction_proto_rawDesc = "" +
	"\n" +
	"#proto/bookkeeping/transaction.proto\x12\vtransaction\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\x10TransactionEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12,\n" +
	"\aentries\x18\x03 \x03(\v2\x12.transaction.EntryR\aentries\"=\n" +
	"\x05Entry\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\x05R\taccountID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\"\x0f\n" +
	"\rGetAllRequest\"X\n" +
	"\vGetAllReply\x12I\n" +
	"\x10transactionEntry\x18\x01 \x03(\v2\x1d.transaction.TransactionEntryR\x10transactionEntry\"m\n" +
	"\rCreateRequest\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12,\n" +
	"\aentries\x18\x02 \x03(\v2\x12.transaction.EntryR\aentries\"X\n" +
	"\vCreateReply\x12I\n" +
	"\x10transactionEntry\x18\x01 \x01(\v2\x1d.transaction.TransactionEntryR\x10transactionEntry\"Z\n" +
	"\rUpdateRequest\x12I\n" +
	"\x10transactionEntry\x18\x01 \x01(\v2\x1d.transaction.TransactionEntryR\x10transactionEntry\"X\n" +
	"\vUpdateReply\x12I\n" +
	"\x10transactionEntry\x18\x01 \x01(\v2\x1d.transaction.TransactionEntryR\x10transactionEntry\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\r\n" +
	"\vDeleteReply2\x95\x02\n" +
	"\vTransaction\x12@\n" +
	"\x06GetAll\x12\x1a.transaction.GetAllRequest\x1a\x18.transaction.GetAllReply\"\x00\x12@\n" +
	"\x06Create\x12\x1a.transaction.CreateRequest\x1a\x18.transaction.CreateReply\"\x00\x12@\n" +
	"\x06Update\x12\x1a.transaction.UpdateRequest\x1a\x18.transaction.UpdateReply\"\x00\x12@\n" +
	"\x06Delete\x12\x1a.transaction.DeleteRequest\x1a\x18.transaction.DeleteReply\"\x00B5Z3internal/domain/bookkeeping/features/transaction/pbb\x06proto3"

var (
	file_proto_bookkeeping_transaction_proto_rawDescOnce sync.Once
	file_proto_bookkeeping_transaction_proto_rawDescData []byte
)

func file_proto_bookkeeping_transaction_proto_rawDescGZIP() []byte {
	file_proto_bookkeeping_transaction_proto_rawDescOnce.Do(func() {
		file_proto_bookkeeping_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bookkeeping_transaction_proto_rawDesc), len(file_proto_bookkeeping_transaction_proto_rawDesc)))
	})
	return file_proto_bookkeeping_transaction_proto_rawDescData
}

var file_proto_bookkeeping_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_bookkeeping_transaction_proto_goTypes = []any{
	(*TransactionEntry)(nil),      // 0: transaction.TransactionEntry
	(*Entry)(nil),                 // 1: transaction.Entry
	(*GetAllRequest)(nil),         // 2: transaction.GetAllRequest
	(*GetAllReply)(nil),           // 3: transaction.GetAllReply
	(*CreateRequest)(nil),         // 4: transaction.CreateRequest
	(*CreateReply)(nil),           // 5: transaction.CreateReply
	(*UpdateRequest)(nil),         // 6: transaction.UpdateRequest
	(*UpdateReply)(nil),           // 7: transaction.UpdateReply
	(*DeleteRequest)(nil),         // 8: transaction.DeleteRequest
	(*DeleteReply)(nil),           // 9: transaction.DeleteReply
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_proto_bookkeeping_transaction_proto_depIdxs = []int32{
	10, // 0: transaction.TransactionEntry.time:type_name -> google.protobuf.Timestamp
	1,  // 1: transaction.TransactionEntry.entries:type_name -> transaction.Entry
	0,  // 2: transaction.GetAllReply.transactionEntry:type_name -> transaction.TransactionEntry
	10, // 3: transaction.CreateRequest.time:type_name -> google.protobuf.Timestamp
	1,  // 4: transaction.CreateRequest.entries:type_name -> transaction.Entry
	0,  // 5: transaction.CreateReply.transactionEntry:type_name -> transaction.TransactionEntry
	0,  // 6: transaction.UpdateRequest.transactionEntry:type_name -> transaction.TransactionEntry
	0,  // 7: transaction.UpdateReply.transactionEntry:type_name -> transaction.TransactionEntry
	2,  // 8: transaction.Transaction.GetAll:input_type -> transaction.GetAllRequest
	4,  // 9: transaction.Transaction.Create:input_type -> transaction.CreateRequest
	6,  // 10: transaction.Transaction.Update:input_type -> transaction.UpdateRequest
	8,  // 11: transaction.Transaction.Delete:input_type -> transaction.DeleteRequest
	3,  // 12: transaction.Transaction.GetAll:output_type -> transaction.GetAllReply
	5,  // 13: transaction.Transaction.Create:output_type -> transaction.CreateReply
	7,  // 14: transaction.Transaction.Update:output_type -> transaction.UpdateReply
	9,  // 15: transaction.Transaction.Delete:output_type -> transaction.DeleteReply
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_bookkeeping_transaction_proto_init() }
func file_proto_bookkeeping_transaction_proto_init() {
	if File_proto_bookkeeping_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bookkeeping_transaction_proto_rawDesc), len(file_proto_bookkeeping_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bookkeeping_transaction_proto_goTypes,
		DependencyIndexes: file_proto_bookkeeping_transaction_proto_depIdxs,
		MessageInfos:      file_proto_bookkeeping_transaction_proto_msgTypes,
	}.Build()
	File_proto_bookkeeping_transaction_proto = out.File
	file_proto_bookkeeping_transaction_proto_goTypes = nil
	file_proto_bookkeeping_transaction_proto_depIdxs = nil
}
