// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: mfa.proto

package pb

import (
	common "fbt/backend/internal/domain/auth/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_mfa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{0}
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotpEnabled   bool                   `protobuf:"varint,1,opt,name=totpEnabled,proto3" json:"totpEnabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_mfa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{1}
}

func (x *StatusReply) GetTotpEnabled() bool {
	if x != nil {
		return x.TotpEnabled
	}
	return false
}

type TOTPValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTPValidateRequest) Reset() {
	*x = TOTPValidateRequest{}
	mi := &file_mfa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTPValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTPValidateRequest) ProtoMessage() {}

func (x *TOTPValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTPValidateRequest.ProtoReflect.Descriptor instead.
func (*TOTPValidateRequest) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{2}
}

func (x *TOTPValidateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type TOTPValidateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTPValidateReply) Reset() {
	*x = TOTPValidateReply{}
	mi := &file_mfa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTPValidateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTPValidateReply) ProtoMessage() {}

func (x *TOTPValidateReply) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTPValidateReply.ProtoReflect.Descriptor instead.
func (*TOTPValidateReply) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{3}
}

func (x *TOTPValidateReply) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type TOTPUpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTPUpsertRequest) Reset() {
	*x = TOTPUpsertRequest{}
	mi := &file_mfa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTPUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTPUpsertRequest) ProtoMessage() {}

func (x *TOTPUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTPUpsertRequest.ProtoReflect.Descriptor instead.
func (*TOTPUpsertRequest) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{4}
}

func (x *TOTPUpsertRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TOTPUpsertReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *common.Session        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TOTPUpsertReply) Reset() {
	*x = TOTPUpsertReply{}
	mi := &file_mfa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOTPUpsertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOTPUpsertReply) ProtoMessage() {}

func (x *TOTPUpsertReply) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOTPUpsertReply.ProtoReflect.Descriptor instead.
func (*TOTPUpsertReply) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{5}
}

func (x *TOTPUpsertReply) GetSession() *common.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_mfa_proto protoreflect.FileDescriptor

const file_mfa_proto_rawDesc = "" +
	"\n" +
	"\tmfa.proto\x12\x03mfa\x1a\x13common/common.proto\"\x0f\n" +
	"\rStatusRequest\"/\n" +
	"\vStatusReply\x12 \n" +
	"\vtotpEnabled\x18\x01 \x01(\bR\vtotpEnabled\")\n" +
	"\x13TOTPValidateRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"-\n" +
	"\x11TOTPValidateReply\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid\"%\n" +
	"\x11TOTPUpsertRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"<\n" +
	"\x0fTOTPUpsertReply\x12)\n" +
	"\asession\x18\x01 \x01(\v2\x0f.common.SessionR\asession2\xbc\x01\n" +
	"\x03MFA\x120\n" +
	"\x06Status\x12\x12.mfa.StatusRequest\x1a\x10.mfa.StatusReply\"\x00\x12B\n" +
	"\fTOTPValidate\x12\x18.mfa.TOTPValidateRequest\x1a\x16.mfa.TOTPValidateReply\"\x00\x12?\n" +
	"\rTOTPUpsertKey\x12\x16.mfa.TOTPUpsertRequest\x1a\x14.mfa.TOTPUpsertReply\"\x00B&Z$internal/domain/auth/features/mfa/pbb\x06proto3"

var (
	file_mfa_proto_rawDescOnce sync.Once
	file_mfa_proto_rawDescData []byte
)

func file_mfa_proto_rawDescGZIP() []byte {
	file_mfa_proto_rawDescOnce.Do(func() {
		file_mfa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mfa_proto_rawDesc), len(file_mfa_proto_rawDesc)))
	})
	return file_mfa_proto_rawDescData
}

var file_mfa_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mfa_proto_goTypes = []any{
	(*StatusRequest)(nil),       // 0: mfa.StatusRequest
	(*StatusReply)(nil),         // 1: mfa.StatusReply
	(*TOTPValidateRequest)(nil), // 2: mfa.TOTPValidateRequest
	(*TOTPValidateReply)(nil),   // 3: mfa.TOTPValidateReply
	(*TOTPUpsertRequest)(nil),   // 4: mfa.TOTPUpsertRequest
	(*TOTPUpsertReply)(nil),     // 5: mfa.TOTPUpsertReply
	(*common.Session)(nil),      // 6: common.Session
}
var file_mfa_proto_depIdxs = []int32{
	6, // 0: mfa.TOTPUpsertReply.session:type_name -> common.Session
	0, // 1: mfa.MFA.Status:input_type -> mfa.StatusRequest
	2, // 2: mfa.MFA.TOTPValidate:input_type -> mfa.TOTPValidateRequest
	4, // 3: mfa.MFA.TOTPUpsertKey:input_type -> mfa.TOTPUpsertRequest
	1, // 4: mfa.MFA.Status:output_type -> mfa.StatusReply
	3, // 5: mfa.MFA.TOTPValidate:output_type -> mfa.TOTPValidateReply
	5, // 6: mfa.MFA.TOTPUpsertKey:output_type -> mfa.TOTPUpsertReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mfa_proto_init() }
func file_mfa_proto_init() {
	if File_mfa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mfa_proto_rawDesc), len(file_mfa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mfa_proto_goTypes,
		DependencyIndexes: file_mfa_proto_depIdxs,
		MessageInfos:      file_mfa_proto_msgTypes,
	}.Build()
	File_mfa_proto = out.File
	file_mfa_proto_goTypes = nil
	file_mfa_proto_depIdxs = nil
}
