// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: mfa.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MFA_Status_FullMethodName        = "/mfa.MFA/Status"
	MFA_TOTPValidate_FullMethodName  = "/mfa.MFA/TOTPValidate"
	MFA_TOTPUpsertKey_FullMethodName = "/mfa.MFA/TOTPUpsertKey"
)

// MFAClient is the client API for MFA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MFAClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	TOTPValidate(ctx context.Context, in *TOTPValidateRequest, opts ...grpc.CallOption) (*TOTPValidateReply, error)
	TOTPUpsertKey(ctx context.Context, in *TOTPUpsertRequest, opts ...grpc.CallOption) (*TOTPUpsertReply, error)
}

type mFAClient struct {
	cc grpc.ClientConnInterface
}

func NewMFAClient(cc grpc.ClientConnInterface) MFAClient {
	return &mFAClient{cc}
}

func (c *mFAClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, MFA_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mFAClient) TOTPValidate(ctx context.Context, in *TOTPValidateRequest, opts ...grpc.CallOption) (*TOTPValidateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TOTPValidateReply)
	err := c.cc.Invoke(ctx, MFA_TOTPValidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mFAClient) TOTPUpsertKey(ctx context.Context, in *TOTPUpsertRequest, opts ...grpc.CallOption) (*TOTPUpsertReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TOTPUpsertReply)
	err := c.cc.Invoke(ctx, MFA_TOTPUpsertKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MFAServer is the server API for MFA service.
// All implementations must embed UnimplementedMFAServer
// for forward compatibility.
type MFAServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	TOTPValidate(context.Context, *TOTPValidateRequest) (*TOTPValidateReply, error)
	TOTPUpsertKey(context.Context, *TOTPUpsertRequest) (*TOTPUpsertReply, error)
	mustEmbedUnimplementedMFAServer()
}

// UnimplementedMFAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMFAServer struct{}

func (UnimplementedMFAServer) Status(context.Context, *StatusRequest) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMFAServer) TOTPValidate(context.Context, *TOTPValidateRequest) (*TOTPValidateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TOTPValidate not implemented")
}
func (UnimplementedMFAServer) TOTPUpsertKey(context.Context, *TOTPUpsertRequest) (*TOTPUpsertReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TOTPUpsertKey not implemented")
}
func (UnimplementedMFAServer) mustEmbedUnimplementedMFAServer() {}
func (UnimplementedMFAServer) testEmbeddedByValue()             {}

// UnsafeMFAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MFAServer will
// result in compilation errors.
type UnsafeMFAServer interface {
	mustEmbedUnimplementedMFAServer()
}

func RegisterMFAServer(s grpc.ServiceRegistrar, srv MFAServer) {
	// If the following call panics, it indicates UnimplementedMFAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MFA_ServiceDesc, srv)
}

func _MFA_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MFAServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MFA_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MFAServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MFA_TOTPValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TOTPValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MFAServer).TOTPValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MFA_TOTPValidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MFAServer).TOTPValidate(ctx, req.(*TOTPValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MFA_TOTPUpsertKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TOTPUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MFAServer).TOTPUpsertKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MFA_TOTPUpsertKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MFAServer).TOTPUpsertKey(ctx, req.(*TOTPUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MFA_ServiceDesc is the grpc.ServiceDesc for MFA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MFA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mfa.MFA",
	HandlerType: (*MFAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _MFA_Status_Handler,
		},
		{
			MethodName: "TOTPValidate",
			Handler:    _MFA_TOTPValidate_Handler,
		},
		{
			MethodName: "TOTPUpsertKey",
			Handler:    _MFA_TOTPUpsertKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mfa.proto",
}
