// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/bookkeeping/account.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDebit       bool                   `protobuf:"varint,3,opt,name=isDebit,proto3" json:"isDebit,omitempty"`
	UserID        string                 `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_bookkeeping_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetIsDebit() bool {
	if x != nil {
		return x.IsDebit
	}
	return false
}

func (x *Account) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_proto_bookkeeping_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_account_proto_rawDescGZIP(), []int{1}
}

type GetAllReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       []*Account             `protobuf:"bytes,1,rep,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllReply) Reset() {
	*x = GetAllReply{}
	mi := &file_proto_bookkeeping_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReply) ProtoMessage() {}

func (x *GetAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReply.ProtoReflect.Descriptor instead.
func (*GetAllReply) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllReply) GetAccount() []*Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDebit       bool                   `protobuf:"varint,2,opt,name=isDebit,proto3" json:"isDebit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_bookkeeping_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetIsDebit() bool {
	if x != nil {
		return x.IsDebit
	}
	return false
}

type CreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReply) Reset() {
	*x = CreateReply{}
	mi := &file_proto_bookkeeping_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReply) ProtoMessage() {}

func (x *CreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReply.ProtoReflect.Descriptor instead.
func (*CreateReply) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_account_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReply) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDebit       bool                   `protobuf:"varint,3,opt,name=isDebit,proto3" json:"isDebit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_bookkeeping_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_account_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRequest) GetIsDebit() bool {
	if x != nil {
		return x.IsDebit
	}
	return false
}

type UpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReply) Reset() {
	*x = UpdateReply{}
	mi := &file_proto_bookkeeping_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReply) ProtoMessage() {}

func (x *UpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReply.ProtoReflect.Descriptor instead.
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateReply) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_bookkeeping_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_account_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_proto_bookkeeping_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookkeeping_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_proto_bookkeeping_account_proto_rawDescGZIP(), []int{8}
}

var File_proto_bookkeeping_account_proto protoreflect.FileDescriptor

const file_proto_bookkeeping_account_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/bookkeeping/account.proto\x12\aaccount\"_\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aisDebit\x18\x03 \x01(\bR\aisDebit\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\tR\x06userID\"\x0f\n" +
	"\rGetAllRequest\"9\n" +
	"\vGetAllReply\x12*\n" +
	"\aaccount\x18\x01 \x03(\v2\x10.account.AccountR\aaccount\"=\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aisDebit\x18\x02 \x01(\bR\aisDebit\"9\n" +
	"\vCreateReply\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.account.AccountR\aaccount\"M\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aisDebit\x18\x03 \x01(\bR\aisDebit\"9\n" +
	"\vUpdateReply\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.account.AccountR\aaccount\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\r\n" +
	"\vDeleteReply2\xf8\x01\n" +
	"\x0eAccountService\x128\n" +
	"\x06GetAll\x12\x16.account.GetAllRequest\x1a\x14.account.GetAllReply\"\x00\x128\n" +
	"\x06Create\x12\x16.account.CreateRequest\x1a\x14.account.CreateReply\"\x00\x128\n" +
	"\x06Update\x12\x16.account.UpdateRequest\x1a\x14.account.UpdateReply\"\x00\x128\n" +
	"\x06Delete\x12\x16.account.DeleteRequest\x1a\x14.account.DeleteReply\"\x00B1Z/internal/domain/bookkeeping/features/account/pbb\x06proto3"

var (
	file_proto_bookkeeping_account_proto_rawDescOnce sync.Once
	file_proto_bookkeeping_account_proto_rawDescData []byte
)

func file_proto_bookkeeping_account_proto_rawDescGZIP() []byte {
	file_proto_bookkeeping_account_proto_rawDescOnce.Do(func() {
		file_proto_bookkeeping_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bookkeeping_account_proto_rawDesc), len(file_proto_bookkeeping_account_proto_rawDesc)))
	})
	return file_proto_bookkeeping_account_proto_rawDescData
}

var file_proto_bookkeeping_account_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_bookkeeping_account_proto_goTypes = []any{
	(*Account)(nil),       // 0: account.Account
	(*GetAllRequest)(nil), // 1: account.GetAllRequest
	(*GetAllReply)(nil),   // 2: account.GetAllReply
	(*CreateRequest)(nil), // 3: account.CreateRequest
	(*CreateReply)(nil),   // 4: account.CreateReply
	(*UpdateRequest)(nil), // 5: account.UpdateRequest
	(*UpdateReply)(nil),   // 6: account.UpdateReply
	(*DeleteRequest)(nil), // 7: account.DeleteRequest
	(*DeleteReply)(nil),   // 8: account.DeleteReply
}
var file_proto_bookkeeping_account_proto_depIdxs = []int32{
	0, // 0: account.GetAllReply.account:type_name -> account.Account
	0, // 1: account.CreateReply.account:type_name -> account.Account
	0, // 2: account.UpdateReply.account:type_name -> account.Account
	1, // 3: account.AccountService.GetAll:input_type -> account.GetAllRequest
	3, // 4: account.AccountService.Create:input_type -> account.CreateRequest
	5, // 5: account.AccountService.Update:input_type -> account.UpdateRequest
	7, // 6: account.AccountService.Delete:input_type -> account.DeleteRequest
	2, // 7: account.AccountService.GetAll:output_type -> account.GetAllReply
	4, // 8: account.AccountService.Create:output_type -> account.CreateReply
	6, // 9: account.AccountService.Update:output_type -> account.UpdateReply
	8, // 10: account.AccountService.Delete:output_type -> account.DeleteReply
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_bookkeeping_account_proto_init() }
func file_proto_bookkeeping_account_proto_init() {
	if File_proto_bookkeeping_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bookkeeping_account_proto_rawDesc), len(file_proto_bookkeeping_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bookkeeping_account_proto_goTypes,
		DependencyIndexes: file_proto_bookkeeping_account_proto_depIdxs,
		MessageInfos:      file_proto_bookkeeping_account_proto_msgTypes,
	}.Build()
	File_proto_bookkeeping_account_proto = out.File
	file_proto_bookkeeping_account_proto_goTypes = nil
	file_proto_bookkeeping_account_proto_depIdxs = nil
}
