# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ENV: test
  PORT: 8080
  PGUSER: postgres
  PGPASSWORD: password
  PGDATABASE: postgres
  PGURL: postgres://postgres:password@localhost:5432/postgres

  ENCRYPTION_KEY: "+TBsWGoCTXFJHW2bBAdCHA=="

  MAIL_ADDRESS: "user@example.com"
  MAIL_SERVER: "smtp.example.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "user"
  MAIL_PASSWORD: "123456"

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12

  test:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: ${{env.PGDATABASE}}
          POSTGRES_USER: ${{env.PGUSER}}
          POSTGRES_PASSWORD: ${{env.PGPASSWORD}}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod download

      - name: migrate database
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@v3.27.3
          goose up
        env:
          GOOSE_DRIVER: postgres
          GOOSE_DBSTRING: ${{env.PGURL}}
          GOOSE_MIGRATION_DIR: ./sqlc/schema

      - name: Test
        run: |
          go install gotest.tools/gotestsum@latest
          gotestsum ./internal/... -cover -coverpkg=./internal/... -coverprofile=cover.out -p=1
          go tool cover -func cover.out -o cover.txt
          cat cover.txt
        env:
          CWD: ${{github.workspace}}

      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        with:
          name: Test-Results
          path: |
            cover.out
            cover.txt

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=cover.out -service=github
